# -*- coding: utf-8 -*-
"""Employee_Retension_using_Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7Aq_NIdQzG1_DGXALy5-cyWyscERRpW

#1: Import Libraries
"""

#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

"""#2: Load Dataset"""

#loading the dataset
df = pd.read_csv("/content/sample_data/HR_comma_sep.csv")

df.head()

"""##a.Exploratory Data Analysis (EDA)[link text](https://)"""

# Dataset Information
df.info()

#Description of data
df.describe()

# check for missing(null) values
df.isnull().sum()

# Correlation Heatmap
plt.figure(figsize=(10,7))

sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap="coolwarm")

plt.title("Correlation Heatmap")
plt.show()

# Employee Retention
df.left.value_counts()

sns.countplot(x='left', data=df)

plt.title("Employee Retention")
plt.show()

# Compare averages of employees who left and stayed
df.groupby('left').mean(numeric_only=True)
# From this table you can observe:

# 1.Satisfaction Level has a strong impact.
# 2.Time spent in company affects retention.
# 3.Number of projects affects retention.
# 4.Average monthly hours also have influence.
# 5.Promotion and work accidents have smaller effects.

# The categorical variables:

# Salary
# Department

# also influence retention.

"""##b.Bar Chart: Salary vs Retention"""

salary_retention = pd.crosstab(df.salary, df.left)

salary_retention.plot(kind='bar',
                      figsize=(7,5))

plt.title("Salary vs Employee Retention")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.show()

"""##c.Bar Chart: Department vs Retention"""

dept_retention = pd.crosstab(df.Department, df.left)

dept_retention.plot(kind='bar',
                    figsize=(12,6))

plt.title("Department vs Employee Retention")
plt.xlabel("Department")
plt.ylabel("Employees")
plt.show()

"""##d.Build Logistic Regression Model"""

# Select Important Features
X = df[['satisfaction_level',
        'average_montly_hours',
        'promotion_last_5years',
        'salary']]

#Convert Salary into Dummy Variables
salary_dummies = pd.get_dummies(X.salary,
                                prefix='salary',
                                drop_first=True)

salary_dummies.head()

# Final Feature Set
X = pd.concat([

    X.drop('salary', axis=1),
    salary_dummies

], axis=1)

X.head()

# Target Variable
y = df.left

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Logistic Regression
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

"""##e.Measure Accuracy"""

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

# Classification Report
print(classification_report(y_test, y_pred))

# Confusion Matrix Visualization
plt.figure(figsize=(5,4))

sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

# Expected Results

# For the provided HR_comma_sep.csv dataset, Logistic Regression typically achieves:

# Accuracy: approximately 76%–79% (depending on train-test split and selected features)
# Key factors affecting employee retention:
# Satisfaction Level (strongest predictor)
# Average Monthly Hours
# Time Spent at Company
# Number of Projects
# Salary
# Promotion in Last 5 Years
# Department has a comparatively weaker impact than salary.

# This workflow satisfies all five project requirements:

# Exploratory data analysis to identify important variables.
# Bar charts showing salary vs. retention.
# Bar charts showing department vs. retention.
# Logistic Regression model using selected features.
# Evaluation using accuracy, confusion matrix, and classification report.